version: '3.7'
services:
  rabbit:
    image: rabbitmq:3-management-alpine
    ports:
      - '5672:5672'
      - '15672:15672'
#    networks:
#      - my-network-name

  redis:
    image: redis:latest
    container_name: 'redis'
    command:
      - redis-server
    ports:
      - '6379:6379'
#    networks:
#      - my-network-name

#  consumer:
#    build: consumer
#    networks:
#      - my-network-name
#    depends_on:
#      - rabbit
#    restart: always

#  app:
#    build: .
#    ports:
#      - '8080:8080
#    networks:
#      - my-network-name
#    depends_on:
#      - rabbit
#    restart: always
#
#networks:
#  my-network-name:
#    driver: bridge
